name: Tests
on: [push]
jobs:
    php-unit-and-functional-tests:
        runs-on: ubuntu-20.04
        # Docs: https://docs.github.com/en/actions/using-containerized-services
        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.2']
        steps:
            # —— Setup GitHub actions —————————————————————————————————————————————
            # https://github.com/actions/checkout (official)
            - name: Git checkout placeholder-service
              uses: actions/checkout@v3
            # https://github.com/shivammathur/setup-php (community)
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: none
                  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
              env:
                  update: true
            - name: Check PHP Version
              run: php -v
            # —— Composer —————————————————————————————————————————————————————————
            - name: Install dependencies
              uses: php-actions/composer@v6
            # —— Symfony ——————————————————————————————————————————————————————————
            - name: Check the Symfony console
              run: bin/console -V
            # —— Tests ———————————————————————————————————————————————————————————
            - name: Run functional and unit tests
              run: |
                make citests
                ls  /var/log/apache2/
                cat /var/log/apache2/error.log
                cat /var/log/apache2/access.log